### PR TITLE
Datamodel add DEFERRABLE INITIALLY DEFERRED

### PR DESCRIPTION
**Pull request by sjib**
Backporting DEFERRABLE INITIALLY DEFERRED also to qgep:

- [x] To all fk_ relations and 
- [x] organisation.fk_dataowner and fk_provider 
- [x] to check if to all other organisation relations also needed.

Hopefully solves https://github.com/QGEP/QGEP/issues/852 and similar INTERLIS import relation errors

### CODE REVIEW

**Comment by sjib** [comment]
- [ ] Will need adaption in import of plugin see TEKSI code:
        self.session_tww.execute(text("SET CONSTRAINTS ALL DEFERRED;"))
https://github.com/teksi/wastewater/blob/bccfbdd9d732ea47e172608363799194329cc7ed/plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_importer_to_intermediate_schema.py#L72

- [ ] TEKSI wastewater sets this also on export
- [ ] https://github.com/teksi/wastewater/blob/3acfba249866d299f8a22e249d9f1e475fe7b88d/plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py#L83

**Comment by sjib** [comment]
- [ ] Find out how a delta file should look like to add DEFERRABLE INITIALLY DEFERRED

**Comment by ponceta** [comment]
Since these are the first deltas for 1.6.2 you have to set current version to 1.6.2 :
https://github.com/QGEP/datamodel/blob/master/system/CURRENT_VERSION.txt

**Review by ponceta — APPROVED** [review]
Thank you for this welcome update!

**Pull request merged**
