### PR TITLE
Swmm roughness translation correction

### PR DESCRIPTION
**Pull request by tproduit**
Add missing parenthesis after check with @TriformMoritz

### CODE REVIEW

**Comment by sjib** [comment]
@tproduit @TriformMoritz Thanks for checking and adaptions.

**Comment by sjib** [comment]
Has someone else the possibility to check this adapted view? @urskaufmann @DflGruBoe

**Comment by sjib** [comment]
@ponceta Should be merged to complete https://github.com/QGEP/qgepplugin/pull/93

**Comment by sjib** [comment]
Should fix https://github.com/QGEP/QGEP/issues/728

**Comment by cymed** [comment]
I checked: there are no overlapping changed lines with #220. The check against Versions 13 and 14 is pending.

**Pull request merged**
