### PR TITLE
Update audit SQL file

### PR DESCRIPTION
**Pull request by lbartoletti**
Update to same version as QWAT. Most notable change add a replay function for pg-history-viewer

### CODE REVIEW

**Comment by ponceta** [comment]
@lbartoletti The delta is missing, that's why Travis is unhappy right?

It would be great to have it! This is really a nice tool!

**Comment by lbartoletti** [comment]
@fredericbonifas Thank you. LGTM.

**Comment by lbartoletti** [comment]
@m-kuhn @3nids OK to merge?

**Comment by m-kuhn** [comment]
@lbartoletti can you add some explanation on the differences? (It would be nice to cover that in the release notes and possibly other places too)
Are there plans for a documentation update?

**Comment by lbartoletti** [comment]
> can you add some explanation on the differences? (It would be nice to cover that in the release notes and possibly other places too)

I copy/paste, the explanation on the QWAT update (dec 2016/jan 2017... I wasn't born yet :D)

> This PR adds:
> 
>     a new function to create a instead of row level trigger for auditing views.
>     a new table logged_relation is added to keep track of identifier columns used to replay updates or deletes for views (primary keys are not accessible through catalog views)
>     a new function replay_event(event_id) is also added to ease replaying stored actions.
> 
> This PR goes in sync with a QGIS plugin (A great Open Source GIS tool) that allows to search logged actions and replay old edits. It can be found here https://github.com/qwat/pg-history-viewer

Why update QGEP as well? To use pg-history-viewer with QGEP, as QWAT, and especially the `replay function` and `logged actions`.


> Are there plans for a documentation update?

Not really, since the document is already available in https://github.com/qwat/pg-history-viewer

**Comment by m-kuhn** [comment]
Thanks.
In this case, I'd be in favour of linking to the existing documentation as a first step at least. Or our average user won't even know he's got to install this plugin :)

**Comment by ponceta** [comment]
@m-kuhn I agree, like we have a section on how to use pg-admin with qgep, we should have a small section for pg-history viewer use on qgep.

https://qwat.github.io/docs/master/fr/html/admin-guide/data_manager.html#qwat-analysis-tools
http://qgep.github.io/docs/fr/admin-guide/index.html

This should be almost the same for QWAT as an admin functionnality for both products.

I've opened another issue to set this up. 

https://git.oslandia.net/Support-projects/helpdesk_qwat_qgep/issues/110

**Comment by ponceta** [comment]
This is the tool, we still need to have :

- **documentation** about the usage and 

- **scripts to enable and disable auditing** when performing pum migrations and 

- **default audited tables** like in QWAT!

See 
https://github.com/qwat/qwat-data-model/blob/7179cae7864773f28c61e060bf36295af0bc57ed/update/delta/pre-all.sql

Otherwise, logs will be polluted with changes coming from deltas.

**Comment by ponceta** [comment]
Here is a sample on history viewer on QGEP using :

SELECT qgep_sys.audit_view('qgep_od.vw_qgep_wastewater_structure', 'true'::boolean, '{}'::text[], '{id}'::text[]);
SELECT qgep_sys.audit_view('qgep_od.vw_qgep_reach', 'true'::boolean, '{}'::text[], '{id}'::text[]);
SELECT qgep_sys.audit_view('qgep_od.vw_cover', 'true'::boolean, '{}'::text[], '{id}'::text[]);
SELECT qgep_sys.audit_view('qgep_od.vw_wastewater_node', 'true'::boolean, '{}'::text[], '{id}'::text[]);

To define auditing on QGEP views

image

**Comment by sjib** [comment]
We have a table od_mutation that could be used for history logging:
https://github.com/QGEP/datamodel/blob/b54504e97cbdb2b3caa85a5ed260136bef20f688/03_qgep_db_dss.sql#L145

How far away is that from your suggestions?

**Comment by ponceta** [comment]
@m-kuhn a first documentation has been update on QWAT. https://qwat.github.io/docs/master/en/html/user-guide/history.html

**Comment by m-kuhn** [comment]
Thanks @ponceta, is the plan to have the docs once in qgep and once in qwat or have it upstream and link to it?

**Comment by ponceta** [comment]
> Thanks @ponceta, is the plan to have the docs once in qgep and once in qwat or have it upstream and link to it?

The simpler the better, I would suggest to have it like easy specific doc on qwat / qgep and complete technical doc upstream.

**Pull request merged**
