### PR TITLE
Changed insert/coalesce

### PR DESCRIPTION
**Pull request by bogdanvaduva**
Just insert/coalesce changes.
Regards

### CODE REVIEW

**Comment by bogdanvaduva** [comment]
Unfortunately I don't have travis knowledge so my last commit was done just to pass its tests.

**Comment by bogdanvaduva** [comment]
ping @m-kuhn 
Any news on the pull request?

**Comment by m-kuhn** [comment]
Looks good to me :) Thanks

**Comment by bogdanvaduva** [comment]
:) Thanks

**Comment by bogdanvaduva** [comment]
@m-kuhn coalesce for inserts are not included yet into the model. When is to expect to be included into the model?
What about the functions for profile?

**Comment by sjib** [comment]
@bogdanvaduva Coalesc is included in the latest model update (26.4.2016) - please check whether ok and then close

**Comment by bogdanvaduva** [comment]
Thanks.

**Comment by sjib** [comment]
Is it ok and can it be closed?

**Comment by m-kuhn** [comment]
It's closed already I think

**Pull request merged**
