### PR TITLE
[WIP] Create plan type views

### PR DESCRIPTION
**Pull request by cymed**
This PR creates a view per plan type for wastewater structures. 
The INSERT works identical to vw_qgep_wastewater_structure but adds a wastewater_structure_symbol. 
The UPDATE updates the elements from vw_qgep_wastewater_structure and Upserts wastewater_structure_symbol.
DELETE only deletes the wastewater_structure_symbol, leaving the other elements untouched.

### CODE REVIEW

**Comment by sjib** [comment]
@cymed Can you rename this **[WIP] Create plan type views**
so it's clear that this will not go in 1.6.1.

**Comment by sjib** [comment]
@cymed Is this ready for 1.6.2? Do we need a delta?

**Comment by cymed** [comment]
Imho it is smarter to close it and port it to tww. Shall I close it here?

**Comment by sjib** [comment]
Yes, please!

**Pull request closed without merging**
