### PR TITLE
Swmm alter views

### PR DESCRIPTION
**Pull request by cymed**
Some of the swmm views were built from a wastewater structure perspective, while a wastewater node perspective is preferrable, The following changes are made:

- dividers are defined as wastewater nodes with two outgoing reaches (overflows are not counted) instead of divider = wastewater node linked to a separating structure (which is problematic when a separating structure has more than one node)
- storage nodes: Assigned to separating structures and infiltration installations based on function/kind. List altered (removed _stormwater retaining channel_ and _stormwater retention channel_, included _pump station_ and  _separating structures_ ). The storages in front of a prank weir with a h-q curve is removed, as they are usually in one of the listed special structures
- junctions are filled with the other nodes
-pump pipes are not exported
- only one generated raingage
- subcatchments link to raingage
- no xsections for pump pipes

### CODE REVIEW

**Comment by cymed** [comment]
views behave differently on postgis 13 and 14, compare both error logs

**Comment by cymed** [comment]
Even though this time the checks have passed, the previous CI checks did not return the same number of tags

| commit | Postgis 13 | Postgis 14|
| ------------- | ------------- | ------------- |
| https://github.com/QGEP/datamodel/pull/230/commits/3f7fca13a9182304d1df9f68c50dcd78ae4fc5d9  | tags: 11507 rows | tags: 11504 rows
| https://github.com/QGEP/datamodel/pull/230/commits/d670f3ea0d8e4da46bab916ed72b473bdf509c46  | tags: 11507 rows   | tags: 11505 rows
| https://github.com/QGEP/datamodel/pull/230/commits/679622519e2c0f934a5e07cfc99f40a4f043bd26 | tags: 11504 rows | tags: 11506 rows
| https://github.com/QGEP/datamodel/pull/230/commits/bf235b7f1a10bc6770417574938b862821fd952c  | tags: 11504 rows  |  tags: 11504 rows |

Note that in all those runs, the sql was not altered. Any Ideas where the problem lies @ponceta?

**Comment by ponceta** [comment]
> Even though this time the checks have passed, the previous CI checks did not return the same number of tags
> 
> commit	Postgis 13	Postgis 14
> [3f7fca1](https://github.com/QGEP/datamodel/commit/3f7fca13a9182304d1df9f68c50dcd78ae4fc5d9)	tags: 11507 rows	tags: 11504 rows
> [d670f3e](https://github.com/QGEP/datamodel/commit/d670f3ea0d8e4da46bab916ed72b473bdf509c46)	tags: 11507 rows	tags: 11505 rows
> [6796225](https://github.com/QGEP/datamodel/commit/679622519e2c0f934a5e07cfc99f40a4f043bd26)	tags: 11504 rows	tags: 11506 rows
> [bf235b7](https://github.com/QGEP/datamodel/commit/bf235b7f1a10bc6770417574938b862821fd952c)	tags: 11504 rows	tags: 11504 rows
> Note that in all those runs, the sql was not altered. Any Ideas where the problem lies @ponceta?

Looking at the logs you now have to adapt the feature counts in the tests since they look to me both identical on postgis 13 and 14 and differ from original implementation since they are now linked to network elements instead of wastewater structures.

**Comment by ponceta** [comment]
https://github.com/QGEP/datamodel/actions/runs/6742150582/job/18327782762?pr=230#step:15:6900 Failure on postgis 14 :(

**Comment by cymed** [comment]
> > Even though this time the checks have passed, the previous CI checks did not return the same number of tags
> > commit	Postgis 13	Postgis 14
> > [3f7fca1](https://github.com/QGEP/datamodel/commit/3f7fca13a9182304d1df9f68c50dcd78ae4fc5d9)	tags: 11507 rows	tags: 11504 rows
> > [d670f3e](https://github.com/QGEP/datamodel/commit/d670f3ea0d8e4da46bab916ed72b473bdf509c46)	tags: 11507 rows	tags: 11505 rows
> > [6796225](https://github.com/QGEP/datamodel/commit/679622519e2c0f934a5e07cfc99f40a4f043bd26)	tags: 11504 rows	tags: 11506 rows
> > [bf235b7](https://github.com/QGEP/datamodel/commit/bf235b7f1a10bc6770417574938b862821fd952c)	tags: 11504 rows	tags: 11504 rows
> > Note that in all those runs, the sql was not altered. Any Ideas where the problem lies @ponceta?
> 
> Looking at the logs you now have to adapt the feature counts in the tests since they look to me both identical on postgis 13 and 14 and differ from original implementation since they are now linked to network elements instead of wastewater structures.

That is the main point: The feature counts differ between CI Checks even though the sql scripts are not altered (!!!)
I would not be bothered if it were only the feature counts differing from the test scripts. I am however confused by feature counts not being identical for PostGIS 13 and 14 and by the Feature counts varying between CI checks although the sql source code is identical.


> https://github.com/QGEP/datamodel/actions/runs/6742150582/job/18327782762?pr=230#step:15:6900 Failure on postgis 14 :( 2023-11-03 06:51:12.566 UTC [166] ERROR: table name "ws_st" specified more than once

Solved by https://github.com/QGEP/datamodel/pull/230/commits/61524578bd1a39dee41a39c8dacebad4a8cc44df

**Pull request closed without merging**
