### PR TITLE
Update Datamodel 2016-04-19

### PR DESCRIPTION
**Pull request by m-kuhn**
Direct replacement for #17 

 * Fix merge problems
 * type `plantype` moved to `qgep.plantype` again

@3nids travis shows some warnings related to the view generator, can you have a look?

### CODE REVIEW

**Comment by 3nids** [comment]
@m-kuhn looking now

**Comment by 3nids** [comment]
@m-kuhn should be ok now

**Comment by m-kuhn** [comment]
Thanks @sjib and @3nids

**Comment by sjib** [comment]
Added qgep.plantype in metadatabase - should be consistent in the future

**Pull request merged**
