### PR TITLE
Added the file with profile functions

### PR DESCRIPTION
**Pull request by bogdanvaduva**
Hi

I created a new pull request for profile functions. 
Regards

### CODE REVIEW

**Comment by m-kuhn** [comment]
I once had a look and I think actually if I would do it again today, I would choose your route instead of the networkx approach chosen originally.

What I am not sure mainly is how to visualize this inside QGIS. So to be compatible with the qgepplugin etc. we will need to fix up some other ends too.

Is this already in use at your end? If yes, we can merge it to make it easier for you to deploy your systems.

**Comment by bogdanvaduva** [comment]
I think it' compatible with qgep plugin (with minor changes) because I use the same javascript scripts from qgep plugin to visualize profiles. 
Yes, I am using it in my systems and it will be great if it's possible to be integrated in the datamodel(Thanks a lot :) ).
I attached a gif file to see it working.
qgep

**Comment by m-kuhn** [comment]
@haubourg, is that what you referring to at the last meeting (recursive pg function)?

**Comment by haubourg** [comment]
Hi Matthias, 
yes I use the same recursive queries for upstream or downstream routing. 
My solution is a little bit hacky, but simple. I only have a recursive query in the data definition filter of a reach layer. The idea is to display only the routes. If you need to use the routing data to find cycles, computes distances, indeed functions on DB side would be better. 
Using that in QGIS server context probably require a server plugin, but I think it's doable :)


See the filter:
```
id in (WITH RECURSIVE search_graph(id, noeud_amont, noeud_aval) AS (
        SELECT id, t.noeud_amont_id as noeud_amont, t.noeud_aval_id as noeud_aval
        FROM ouvrage.troncon t where id = 
                /*&*/'17d02d32-88b5-494f-a9c8-e9ea40f03601'/*&*/
      UNION 
        SELECT t.id, t.noeud_amont_id as noeud_amont, t.noeud_aval_id as noeud_aval
        FROM ouvrage.troncon t, search_graph sg
        WHERE (
         t.noeud_amont_id = sg.noeud_aval
         ) 
       
)

SELECT distinct tr.id FROM search_graph         
join ouvrage.troncon tr on search_graph.id = tr.id
limit 2000 
)
```

Changing the startpoint for routing is done by a python action on a reach just doing a hacky regexp replace between the magic /*&*/ comment delimiters :)

```
# coding: utf8 
from qgis.gui import QgsMessageBar
import re

registry = QgsMapLayerRegistry.instance()
layer = registry.mapLayer('[% @layer_id %]')
parcours_layer  = registry.mapLayer('ID_COUCHE_PARCOURS_RESEAU')
filter = parcours_layer.subsetString()
newFilter= re.sub('&.*&', '&*/\'[%id%]\'/*&' , filter, flags=re.DOTALL) 
parcours_layer.setSubsetString(newFilter)

```

a preview:

anim

**Comment by mdouchin** [comment]
Hi,

I propose the following some minor changes in your SQL scripts:

* Cast the ST_AsGeoJSON into JSON via ::json -> this creates a valid JSON file (otherwise all geometries are treated like text, and quotes are escaped with \\ )
* Replace vw_qgep_cover by vw_qgep_wastewater_structure

```
--- /tmp/12_profile_functions.sql
+++ /home/mdouchin/Documents/3liz/CA_Soissonnais/qgep/scripts/fonction_fn_profil.sql
@@ -128,7 +128,7 @@
 			) as rp
 		) as "reachPoints",
 		r.type as "type",
-		ST_AsGeoJSON(r.progression_geometry) as "geometry"
+		ST_AsGeoJSON(r.progression_geometry)::json as "geometry"
 		) as l;
 
 -- We add reaches to result
@@ -194,7 +194,7 @@
 			) as "reachPoints",
 			s.type as "type",
 			CASE WHEN res.cover_level IS NULL THEN 0.0 ELSE res.cover_level END as "coverLevel",
-			ST_AsGeoJSON(res.situation_geometry) as "geometry"
+			ST_AsGeoJSON(res.situation_geometry)::json as "geometry"
 	) as st;
 	
 -- We add structure to result
@@ -279,17 +279,17 @@
 SELECT obj_id
 FROM qgep.vw_qgep_reach
 WHERE (rp_from_fk_wastewater_networkelement = (
-SELECT wn_obj_id FROM qgep.vw_qgep_cover
+SELECT wn_obj_id FROM qgep.vw_qgep_wastewater_structure
 WHERE obj_id=cover_obj_id
 ) OR
  rp_to_fk_wastewater_networkelement = (
-SELECT wn_obj_id FROM qgep.vw_qgep_cover
+SELECT wn_obj_id FROM qgep.vw_qgep_wastewater_structure
 WHERE obj_id=cover_obj_id
 ) 
 )
 AND 
 ST_Dwithin(ST_EndPoint(qgep.vw_qgep_reach.progression_geometry),
-	(SELECT situation_geometry FROM qgep.vw_qgep_cover
+	(SELECT situation_geometry FROM qgep.vw_qgep_wastewater_structure
 	WHERE obj_id=cover_obj_id),0.1)
 ) LIMIT 1;$BODY$
   LANGUAGE sql VOLATILE
@@ -313,17 +313,17 @@
 SELECT obj_id
 FROM qgep.vw_qgep_reach
 WHERE (rp_from_fk_wastewater_networkelement = (
-SELECT wn_obj_id FROM qgep.vw_qgep_cover
+SELECT wn_obj_id FROM qgep.vw_qgep_wastewater_structure
 WHERE obj_id=cover_obj_id
 ) OR
  rp_to_fk_wastewater_networkelement = (
-SELECT wn_obj_id FROM qgep.vw_qgep_cover
+SELECT wn_obj_id FROM qgep.vw_qgep_wastewater_structure
 WHERE obj_id=cover_obj_id
 ) 
 )
 AND 
 ST_Dwithin(ST_StartPoint(qgep.vw_qgep_reach.progression_geometry),
-	(SELECT situation_geometry FROM qgep.vw_qgep_cover
+	(SELECT situation_geometry FROM qgep.vw_qgep_wastewater_structure
 	WHERE obj_id=cover_obj_id),0.1)
 ) LIMIT 1;$BODY$
   LANGUAGE sql VOLATILE

```

I also think you should revert Start and End points for the functions dedicated to find the next reach for upstream and downstream functions. Otherwise I have to use the opposite function to get the right first reach, like this (which seems counter-intuitive):

```
-- Get all downstream reaches
SELECT geometry
FROM qgep.fn_downstream( qgep.fn_reach_for_upstream('some_manhole_id') );

-- Get upstream reaches
SELECT geometry
FROM qgep.fn_upstream( qgep.fn_reach_for_downstream('some_manhole_id') );
```

**Comment by olivierdalang** [comment]
(closing this, as it seems it's been sleeping for over 5 years :-) feel free to reopen if it still applies)

**Pull request closed without merging**
