### PR TITLE
Update datamodel 20151016

### PR DESCRIPTION
**Pull request by sjib**
New export of datamodel from Metadatabase, added triggers

### CODE REVIEW

**Comment by sjib** [comment]
ERROR: test_last_modified (test_triggers.TestTriggers) @m-kuhn can you look into that - model is now ok but test failed. Thanks

**Comment by sjib** [comment]
Or do we need also the new views?

**Comment by sjib** [comment]
Additional _geometry also added after line 112 in master of vw_cover https://github.com/QGEP/datamodel/blob/master/view/vw_cover.sql#L112

**Comment by sjib** [comment]
psql:/home/travis/build/QGEP/datamodel/scripts/../view/vw_cover.sql:100: ERROR:  relation "qgep.vw_cover" does not exist

**Comment by m-kuhn** [comment]
You commented the `CREATE VIEW` part in your latest commit https://github.com/QGEP/datamodel/commit/0219480727625e9b5a50c1dc8247e03dea2427ea

**Comment by sjib** [comment]
@m-kuhn ERROR: test_last_modified (test_triggers.TestTriggers) [Line 170] (https://travis-ci.org/QGEP/datamodel/builds/86388088#L170)

**Comment by m-kuhn** [comment]
Compare the example:
https://github.com/QGEP/datamodel/blob/master/03_qgep_db_dss.sql#L1843
to your implementation:
https://github.com/QGEP/datamodel/blob/update-datamodell-20151018/03_qgep_db_dss.sql#L2306

**Comment by m-kuhn** [comment]
https://travis-ci.org/QGEP/QGEP/builds/86580745#L158-L159

> psql:/home/travis/build/QGEP/QGEP/scripts/../migration08/02_od_wastewater_structure.sql:91: ERROR:  insert or update on table "od_wastewater_structure" violates foreign key constraint "fkey_vl_wastewater_structure_status"
DETAIL:  Key (status)=(6528) is not present in table "vl_wastewater_structure_status".

@sjib do you know why this could have happened in the migration step?

**Comment by sjib** [comment]
Yes I think that not all values of status were migrated to the latest model version (20151018).

We have changed back “in_Betrieb.in_Betrieb” back to “in_Betrieb” because now INTERLIS allows us to avoid these double values in hierachic value list. That was not possible with the 2014 version.

**Comment by m-kuhn** [comment]
How do we fix this? Which values need to change?

**Comment by sjib** [comment]
Migration Script has to match with this:
https://github.com/QGEP/datamodel/blob/master/03_qgep_db_dss.sql#L4080

So change line https://github.com/QGEP/QGEP/blob/master/migration08/02_od_wastewater_structure.sql#L67 
WHEN status = 5 THEN 6528 --- operational.operational
to
WHEN status = 5 THEN 8493 --- operational

**Comment by m-kuhn** [comment]
Are there other changes between the last and this model release? Are the changes documented somewhere?

**Comment by sjib** [comment]
Yes, they are documented here on the "Gelbdruckliste": https://www.vsa.ch/fachbereiche-cc/siedlungsentwaesserung/datenstruktur-siedlungsentwaesserung/gelbdrucke/

**Pull request merged**
