### PR TITLE
Create `vw_infiltration_installation` and `vw_wwtp_structure` views

### PR DESCRIPTION
**Pull request by rbovard**
Fix https://github.com/QGEP/QGEP/issues/768

Create `vw_infiltration_installation` and `vw_wwtp_structure` views.

~Please double check the diff file, I created it manually.~

~*BTW, is there a way to automatically create this diff (maybe with PUM)?*~

### CODE REVIEW

**Comment by ponceta** [comment]
@rbovard Nope nope nope, no delta is required on views, that's precisely why we drop and create these dynamically.

Without the delta CI should be fine!

**Comment by sjib** [comment]
@rbovard My fault with the delta. Just for datamodel changes.

**Comment by ponceta** [comment]
CI is happy, safe to merge since this is only two additionnal views.

**Comment by ponceta** [comment]
Thank you @rbovard !

**Pull request merged**
