### PR TITLE
Interpolate z of reaches' progression_geometry

### PR DESCRIPTION
**Pull request by cymed**
fixes [#759](https://github.com/QGEP/QGEP/issues/759)

### CODE REVIEW

**Comment by cymed** [comment]
Downside of this solution: does not work with reaches that have duplicate nodes

**Comment by sjib** [comment]
Duplicate nodes in a reach should be eliminated anyway - will cause problems on the INTERLIS export.

**Comment by ponceta** [comment]
Should be tested for durability issues like :
https://github.com/QGEP/datamodel/blob/master/test/test_triggers.py

**Comment by cymed** [comment]
Docker is failing due to the :SRID in the delta. How can I fix this?

**Comment by olivierdalang** [comment]
> Docker is failing due to the :SRID in the delta. How can I fix this?

In the delta, you should use `%(SRID)s` instead (that variable will be set by PUM).

**Review by olivierdalang — CHANGES_REQUESTED** [review]
Some notes:

- [ ] in line with what we're doing in https://github.com/QGEP/datamodel/pull/146, we should rather drop/recreate functions in pre/post all, instead of creating a delta. Otherwise, any slight modification of the function will result in a delta. This means the code for the function would move under `./views` (which already not only contains views)

- [ ] to me, it's not clear what the goal of this PR is. It creates a new function, but I don't see it used anywhere ? Or am I missing something ? If it's meant as a helper function to be run manually, we probably at least would require some docs. If not you're probably missing triggers.

- [ ] if meant as a helper function, it would be better to implement this as a QGIS algorithm, otherwise the datamodel will quickly be cluttered with util functions that need to be maintained. I'd recommend searching first if by any chance it does not already exist in an existing plugin

**Comment by cymed** [comment]
It is not used anywhere at the moment, correct. There are discussions going on whether to include it in a trigger or not. Until then, I suggest to close this PR and reuse the code once the trigger functionalities are defined.

**Pull request closed without merging**
