### PR TITLE
UpdateVSAKEK20161024

### PR DESCRIPTION
**Pull request by sjib**
fixed:  qgep.od_damage ADD COLUMN fk_examination
fixed: od_file misses references to data_media

### CODE REVIEW

**Comment by sjib** [comment]
Trying to fix [#237] https://github.com/QGEP/QGEP/issues/237
and include
[KEK fix damage - examination] (https://github.com/QGEP/datamodel/commit/32aba7cf3f3fe2e1f59c388e66a62f25ed888951)

**Comment by 3nids** [comment]
Thanks @sjib 
There is an error `sql:/home/travis/build/QGEP/datamodel/scripts/../04_vsa_kek_extension.sql:82: ERROR:  column "dataowner" of relation "qgep.od_damage" does not exist`, it should be `fk_dataowner`
Can you fix this?

**Comment by sjib** [comment]
2nd attempt with corrected error fk_dataowner / fk_provider at COMMENTS.
@3nids Why do I still get checks failing?

**Comment by m-kuhn** [comment]
Something with the italian translation of the KEK extension seems to go wrong

https://travis-ci.org/QGEP/datamodel/builds/170491988#L191

    04_vsa_kek_extension.sql:224: ERROR:  column "value_it" of relation "vl_examination_recording_type" does not exist

**Comment by sjib** [comment]
I will check

Thanks @sjib <https://github.com/sjib>  
There is an error sql:/home/travis/build/QGEP/datamodel/scripts/../04_vsa_kek_extension.sql:82: ERROR: column "dataowner" of relation "qgep.od_damage" does not exist, it should be fk_dataowner
Can you fix this?

**Comment by sjib** [comment]
Can I do this also in a way that columns are just added if they do not exist yet?

ALTER TABLE qgep.is_value_list_base ALTER COLUMN value_it character varying (50);

**Comment by sjib** [comment]
@tudorbarascu Conflicts now with generate_ro_columns.sql

**Comment by tudorbarascu** [comment]
@sjib  That file (which is in the top directory.. same as 04_vsa_kek_extension.sql) came with  https://github.com/QGEP/datamodel/commit/c01f826be340595659c1dad06ed05a3f7f1320d3 . So you need to also delete the ``psql "service=${PGSERVICE}" -v ON_ERROR_STOP=1 -f ${DIR}/generate_ro_columns.sql`` from the ``db_setup.sh`` file.

I think git will do it automatically for you If you revert that specific commit with ``git revert c01f826be340595659c1dad06ed05a3f7f1320d3``

**Comment by 3nids** [comment]
@sjib can this be closed?

**Pull request closed without merging**
