### PR TITLE
Maintenance_event views that can be underlayed on maps

### PR DESCRIPTION
**Pull request by urskaufmann**

### CODE REVIEW

**Comment by sjib** [comment]
@m-kuhn Please merge to master

**Comment by 3nids** [comment]
Please wait a bit, I will take care of it

**Comment by 3nids** [comment]
@urskaufmann sorry for the delay.
Do you plan to add these views in the QGIS project?
And in the main DB setup script?

**Comment by 3nids** [comment]
manually merged

**Pull request closed without merging**
