### PR TITLE
create on delete rule on qgep_od.reach

### PR DESCRIPTION
**Pull request by signedav**
deleting reach_points and wastewater_networkelement.
and remove these deleting statements from rule of vw_qgep_reach.

fixes #436

To do:
- [x] Tests

### CODE REVIEW

**Comment by urskaufmann** [comment]
I have tested in my demoproject: perfect! 
To do as you write: deleting of wastewater structure and channel (or...), if there is now other networkelement connected.

**Comment by m-kuhn** [comment]
Thanks @signedav 
Please delete the branch (or even better, make new working branches on a private fork, then I don't care if it's deleted or not ;) )

**Comment by sjib** [comment]
Does this also fix https://github.com/QGEP/QGEP/issues/333 ?

**Comment by signedav** [comment]
Yes @sjib

**Pull request merged**
