### PR TITLE
Create SQL code for changing reach direction

### PR DESCRIPTION
**Pull request by max-trolliet**

### CODE REVIEW

**Comment by varrieta** [comment]
Is this link to issue #380 ?

**Comment by max-trolliet** [comment]
Yes it is, we worked on that with Mathias yesterday. SQL is working. Python is on its way in the pluggin. It was is order to go on with this matter during the codesprint.

**Comment by max-trolliet** [comment]
Not yet. We'll see about that at the code sprint?

**Comment by varrieta** [comment]
Sure. 

Or you can add the two lines below in your code? (not sure it is that simple)
`, fk_reach_point_from = fk_reach_point_to
                , fk_reach_point_to = fk_reach_point_from`

**Comment by m-kuhn** [comment]
Final suggestion applied (also changes reach now).
I guess missing now is

* execute from setup_db.sh
* execute in delta

@3nids anything else?

**Comment by 3nids** [comment]
> execute from setup_db.sh
execute in delta

exactly, also commenting the function (documentation) would be cool too

**Comment by max-trolliet** [comment]
I'll get on the comment as soon as I have it running at work.

**Pull request merged**
