### PR TITLE
Import only verified element

### PR DESCRIPTION
**Pull request by varrieta**
To send only elements that where verified on the field to quarantaine.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks @varrieta 
Can you indent the existing IF-block by one more level for readability?
For the rest, can you have a look @signedav ?

**Comment by varrieta** [comment]
I just did, but not sure I did it correctly?

**Comment by m-kuhn** [comment]
No worries, just leave the commit it doesn't hurt
@signedav here's the diff without whitespaces

https://github.com/QGEP/datamodel/pull/88/files?utf8=%E2%9C%93&diff=split&w=1

**Comment by 3nids** [comment]
Is anyone planing on updating this? @signedav @varrieta

**Comment by signedav** [comment]
Thanks for remembering. I don't really know about the status. @varrieta should I update it?

**Comment by varrieta** [comment]
Yes thanks!

**Comment by signedav** [comment]
Hm... Sorry, it seems that I cannot edit this branch. Possibly because I'm not a maintainer or because I do something wrong :upside_down_face: 

If it's possible for you @varrieta to add the mentioned line to the end of your delta file, you could do it yourself.
```
LANGUAGE plpgsql;
```
And resolve the merge conflict? (tell me if you need help on that)

Or I could make a new branch with a new PR and you don't have to do anything. Just tell me.

**Comment by varrieta** [comment]
I modified the delta file.
How can I resolve the conflitcs?

**Comment by signedav** [comment]
Easiest would be to make it over the browser: Go to "Resolve conflicts" 
image

Then delete the line 55, 224, 225 and 226 and mark it as resolved here:
image

**Comment by varrieta** [comment]
Done? :)

**Comment by signedav** [comment]
Hm... There is something wrong. Possibly I told you wrong. 

You should remove the `=======`  and keep the `SELECT set_config('qgep.srid', :SRID::text, false);`

image

**Comment by varrieta** [comment]
Better?

**Comment by signedav** [comment]
Hi @varrieta I found out that it's more complex than I thought. The function you are improving with this PR is moved meanwhile to another file. Means we cannot just merge like I advised you, sorry.

Means I suggest to do the following:
- checkout and pull master
- create new branch e.g. patch-6b
- edit the file `view/vw_qgep_import.sql` (instead of `13_import.sql`) with your changes including the Matthias' indentation
- make new pull request and we see again
- close this pull request

If you don't mind, when I "steal" your commits, then I can do it for you.

**Pull request closed without merging**
