### PR TITLE
Update Datamodel 20160419

### PR DESCRIPTION
**Pull request by sjib**
Correction ON DELETE

### CODE REVIEW

**Comment by sjib** [comment]
Changed detail_geometry_3d_geometry to detail_geometry3d_geometry, dito to new progression3d_geometry. Adapations of datamodel and view vw_channel and vw_discharge_point etc.

**Comment by sjib** [comment]
Datemodel ok - next step is updating meta information

**Comment by sjib** [comment]
Dictionaries for dss and kek ok - next step update vsakek datamodel

**Comment by sjib** [comment]
fix_vsa_kek_extension.sql:2: ERROR:  column "damage_code_manhole" does not exist - run without # psql "service=${PGSERVICE}" -v ON_ERROR_STOP=1 -f ${DIR}/fixes/fix_vsa_kek_extension.sql

**Comment by sjib** [comment]
27.4.2016 qgep.od_examination ADD COLUMN operator commented out, duplicate already in od_maintenance_event

**Comment by sjib** [comment]
@m-kuhn Datamodel changes VSA-DSS and VSA-KEK passed ok - can you integrate in master?

**Comment by m-kuhn** [comment]
Thanks Stefan, this looks very good now.
Only some minor corrections had to be applied.

Further processing in #18

**Pull request closed without merging**
