### PR TITLE
Labeling of wastewater structures with multiple wastewater nodes

### PR DESCRIPTION
**Pull request by cymed**
According to VSA-DSS, a wastewater structure with a leaping weir is represented with two wastewater nodes see [VSI-Wiki](https://vsa.ch/wiki/regenueberlauf-mit-streichwehr/). This requires us to partition the input and output labels by NE.fk_wastewater_structure instead of RP.fk_wastewater_networkelement. 

Additionally, I added two other enhancements:

1. Covers are enumerated
2. The enumeration index is only added if there is more than one input/output/cover.

### CODE REVIEW

**Comment by sjib** [comment]
@urskaufmann Can you test this new symbology and give a feedback?

**Comment by ponceta** [comment]
This should make the CI fail through the test on cover label which is yet indexed, test should be adapted according to this development.

**Comment by ponceta** [comment]
This looks interesting :

```
- ('qgep_od', 'update_wastewater_structure_label', 'boolean', "\n  DECLARE\n  m
+ ('qgep_od', 'update_wastewater_structure_label', 'boolean', "\n  DECLARE\n  m
- ('qgep_od', 'update_wastewater_structure_label', 'text', "\n  DECLARE\n  myre
+ ('qgep_od', 'update_wastewater_structure_label', 'text', "\n  DECLARE\n  myre
```

Function looks different even if the code modification and the delta are identical... :-(

**Comment by ponceta** [comment]
Test to adapt :

```
expected_values_for_field = {'_bottom_label': '\nB=90.12', '_cover_label': '\nC=[98](https://github.com/QGEP/datamodel/actions/runs/3702151185/jobs/6272111255#step:7:99).00', '_input_label': '\nI1=95.00', '_label': 'B', ...}

    def check_values(expected_values_for_field):
        row = self.select('vw_qgep_wastewater_structure', strct_id)
        for field, expected_value in expected_values_for_field.items():
>           assert row[field] == expected_value, "Field {} is incorrect: {} instead of {}".format(
                field, repr(row[field]), repr(expected_value)
            )
E           AssertionError: Field _input_label is incorrect: '\nI=95.00' instead of '\nI1=95.00'
E           assert '\nI=95.00' == '\nI1=95.00'
E               
E             - I1=95.00
E             ?  -
E             + I=95.00

test/test_triggers.py:85: AssertionError
=========================== short test summary info ============================
FAILED test/test_triggers.py::TestTriggers::test_labels - AssertionError: Fie...
========================= 1 failed, 26 passed in 5.18s =========================
Error: Process completed with exit code 1.
```

**Comment by ponceta** [comment]
@cymed tests are green and this is how it looks like on the demo project.

Do we provide the symbology update in the delta? 

- [ ] `SELECT qgep_od.update_wastewater_structure_label(NULL,true);`

Please remove the WIP label in your PR Title if satisfied with the result.

image

**Pull request merged**
