### PR TITLE
Fix translation error in english for pump.construction_type

### PR DESCRIPTION
**Pull request by sjib**
pump.contruction_type should be pump.construction_type sein (Bauart) - translation error in English

### CODE REVIEW

**Comment by sjib** [comment]
@olivierdalang Why does this fail with
`Run LAST_VERSION=$(ls delta | sort -r | sed '/^delta_/!d' | head -n 1 | cut -d_ -f2)
Version mismatch 1.5.7 != 1.5.6
Error: Process completed with exit code 1.`

Do we first have to merge 1.5.6?

**Comment by olivierdalang** [comment]
You need to update `system/CURRENT_VERSION.txt` too (not sure of the exact purpose of this file)

**Comment by ponceta** [comment]
- [ ] Provide base code fix for manual initialization of QGEP.

**Comment by sjib** [comment]
- [ ] to do - make correction also in 03_qgep_db_dss.sql and 09_qgep_dictionaries.sql

**Comment by sjib** [comment]
@ponceta Is this implemented? https://github.com/QGEP/datamodel/pull/183#issuecomment-1344035704

**Comment by sjib** [comment]
> You need to update system/CURRENT_VERSION.txt too (not sure of the exact purpose of this file)
@ponceta Can you provide me with the next delta number for this?

**Comment by ponceta** [comment]
@sjib please rename your delta to 1.5.7

**Comment by sjib** [comment]
@ponceta Checks fail - Error: Process completed with exit code 137.
Do you know why?

**Pull request merged**
