### PR TITLE
Fix special_structure insert function

### PR DESCRIPTION
**Pull request by ponceta**
ss_function instead of ss_special_structure_function

### CODE REVIEW

**Comment by 3nids** [comment]
thanks a lot, can you add a delta along?

**Comment by 3nids** [comment]
mainly being a copy of the SQL file

**Comment by 3nids** [comment]
no worries, I'll do it, I have another PR on the same view

**Comment by ponceta** [comment]
Yes, I'm still thinking that deltas on views are an aberration.

I'm trying migration on new datamodel. We'll see if I find some more before doing anything. Just leaving this here as remember note.

**Comment by m-kuhn** [comment]
> Yes, I'm still thinking that deltas on views are an aberration.

I think we are all on the same page here, would be nice to address that at some point

**Comment by 3nids** [comment]
integrated in #71

**Comment by 3nids** [comment]
https://github.com/QGEP/datamodel/pull/71/commits

**Comment by ponceta** [comment]
@3nids Thanks!

**Pull request closed without merging**
