### PR TITLE
add damage view creation

### PR DESCRIPTION
**Pull request by 3nids**
this also updates metaproject submodule which now use a python function instead of plpgsql

also dirty fix for quantification fields (varchar vs integer)

### CODE REVIEW

**Comment by 3nids** [comment]
@m-kuhn I don't understand, it works well locally. Can you have a quick look please?
Cheers!

**Comment by sjib** [comment]
Hello Denis

Quantification1 and 2 have to be varchar – not all allowed values fit into integer!!!

**Comment by m-kuhn** [comment]
@3nids the travis build is fixed
I think the issue with datatype has to be still sorted out before merging

And nice job with the script invocation in -c

**Comment by 3nids** [comment]
ok, thanks a lot!
indeed, the code for view creation is a lot nicer than before!
I will change the quantification type and merge if it's ok for you.
cheers

**Comment by m-kuhn** [comment]
Proceed as you wish

**Comment by 3nids** [comment]
thanks @sjib

**Pull request merged**
